[package]
name = "image"
version = "0.2.0-alpha.4"
license = "MIT"
description = "A pure rust imaging library. Note that there is a bug in crates.io use image = \"~0.2.0\" for your dependency instead of the suggested one."
authors = [
    "ccgn",
    "bvssvni <bvssvni@gmail.com>",
    "nwin",
    "TyOverby <ty@pre-alpha.com>"]
readme = "README.md"
documentation = "http://www.rust-ci.org/PistonDevelopers/piston/doc/image/index.html"
repository = "https://github.com/PistonDevelopers/image.git"
homepage = "https://github.com/PistonDevelopers/image"
exclude = [
    "src/png/testdata/*",
    "examples/*",
    "tests/*",
]
[lib]
name = "image"
path = "./src/lib.rs"

[dependencies.num]
git = "https://github.com/rust-lang/num"

[dev-dependencies.glob]
git = "https://github.com/rust-lang/glob"

[dependencies.zlib]
git = "https://github.com/sivadeilra/zlib"