[package]
name = "image"
version = "0.21.0"
license = "MIT"
description = "Imaging library written in Rust. Provides basic filters and decoders for the most common image formats."
authors = [
    "ccgn",
    "bvssvni <bvssvni@gmail.com>",
    "nwin",
    "TyOverby <ty@pre-alpha.com>",
    "HeroicKatora",
    "Calum",
    "CensoredUsername <cens.username@gmail.com>",
    "fintelia <fintelia@gmail.com>"
]
readme = "README.md"
documentation = "https://docs.rs/image"
repository = "https://github.com/PistonDevelopers/image.git"
homepage = "https://github.com/PistonDevelopers/image"
categories = ["multimedia::images", "multimedia::encoding"]
exclude = [
    "src/png/testdata/*",
    "examples/*",
    "tests/*",
]

[lib]
name = "image"
path = "./src/lib.rs"

[dependencies]
byteorder = "1.3.1"
num-iter = "0.1.37"
num-rational = { version = "0.2.1", default-features = false }
num-traits = "0.2.6"
lzw = "0.10.0"
safe-transmute = "0.10.1"

[dependencies.gif]
version = "0.10.1"
optional = true

[dependencies.jpeg-decoder]
version = "0.1.15"
default-features = false
optional = true

[dependencies.png]
version = "0.14.0"
optional = true

[dependencies.scoped_threadpool]
version = "0.1.9"
optional = true

[dependencies.tiff]
version = "0.2.2"
optional = true

[dev-dependencies]
num-complex = "0.2.1"
glob = "0.2.11"
quickcheck = "0.8.1"

[features]
default = ["gif_codec", "jpeg", "ico", "png_codec", "pnm", "tga", "tiff", "webp", "bmp", "hdr", "dxt", "jpeg_rayon"]

gif_codec = ["gif"]
ico = ["bmp", "png_codec"]
jpeg = ["jpeg-decoder"]
png_codec = ["png"]
pnm = []
tga = []
webp = []
bmp = []
hdr = ["scoped_threadpool"]
dxt = []
jpeg_rayon = ["jpeg-decoder/rayon"]

benchmarks = []
